# Configuration location
config-directory=config
secret-provider=vault

# Generic properties
spring.application.name=MicroSpringTodoWebApp
server.port=8080
spring.threads.virtual.enabled=true

# Actuator
management.server.port=9000

# Logs
logging.level.com.robottx.todo=DEBUG