service-config.valkeyHostname=localhost
service-config.valkeyPort=6379
service-config.valkeyUsernameSecretName=ValkeyUsername
service-config.valkeyPasswordSecretName=ValkeyPassword

service-config.applicationRealm=applications
service-config.applicationClientId=todo-service-server
service-config.applicationClientSecretName=ApplicationsClientSecret
service-config.authorizationServerUri=http://localhost:1080/realms/applications/protocol/openid-connect/auth
service-config.authorizationServerTokenUri=http://localhost:1080/realms/applications/protocol/openid-connect/token
service-config.authorizationServerJwksUri=http://localhost:1080/realms/applications/protocol/openid-connect/certs
service-config.todoApiUri=http://localhost:1080/api/v1/
